### PR TITLE
[DOC IMP] Conventions of Chinese translation for Zigbee Boot Camp

### PR DESCRIPTION
**Pull request by ChengYuan-CY**
**Description about the pull request**
Add the "Conventions of Chinese translation" for Zigbee Boot Camp project.

**Review**
@MarkDing @Jim-tech

### CODE REVIEW

**Comment by Jim-tech** [comment]
add some more words:

Term
-|
WSTK|

English | Chinese
-|-|
Project | 项目 / 工程 选定一个
Hands-on | 实验

**Comment by MarkDing** [comment]
"Image" no Chinese?
Tab 选项卡或标签?

**Comment by jessizheng** [comment]
@ChengYuan-CY  add some words:
|Term|
|:-|
|image|
|Trust Center|
|Network Analyzer|
|ZigBee 3.0 Security|

|English|Chinese|
|:-|:-|
|Tab|选项卡|
|Program|烧录|
|Project|项目|
|Node|节点|
|Network forming|网络创建|
|Replay|重发|
|Stack|协议栈|
|Exercise|实验|

**Comment by jessizheng** [comment]
|Term|
|:-|
|Zigbee 预备课程|
|Zigbee 预备课程反馈|

**Comment by ChengYuan-CY** [comment]
Thanks a lot for the comments. 
I'm going to close this pull request since the forked branch was deleted by mistake on my side. The commit will be combined to pull request #62. Thanks again.

**Pull request closed without merging**
